#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      web-search.sh
#   created:   24.02.2017.-08:59:54
#   revision:  ---
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   rofi
# Description:
#   Use rofi to search the web.
# Usage:
#   web-search.sh
# -----------------------------------------------------------------------------
# Script:

declare -A URLS
declare -A ICONS

URLS=(
  ["google"]="https://www.google.com/search?q="
  ["duckduckgo"]="https://www.duckduckgo.com/?q="
  ["github"]="https://github.com/search?q="
  ["stackoverflow"]="http://stackoverflow.com/search?q="
  ["superuser"]="http://superuser.com/search?q="
  ["askubuntu"]="http://askubuntu.com/search?q="
  ["youtube"]="https://www.youtube.com/results?search_query="
  ["azlyrics"]="https://search.azlyrics.com/search.php?q="
)

ICONS=(
  ["google"]=""
  ["duckduckgo"]=""
  ["github"]=""
  ["stackoverflow"]=""
  ["superuser"]=""
  ["askubuntu"]=""
  ["youtube"]=""
  ["azlyrics"]=""
)

# List for rofi
gen_list() {
    for i in "${!URLS[@]}"
    do
      echo "${i}"
    done
}

main() {
  # Pass the list to rofi
  platform=$( (gen_list) | rofi -dmenu -no-custom -p "" )

  if [[ -n "$platform" ]]; then
    if [[ ${ICONS[$platform]} = "" ]]; then
        query=$( (echo " Go back") | rofi -dmenu -lines 1 -p "${platform[@]^}" )
    else
        query=$( (echo " Go back") | rofi -dmenu -lines 1 -p "${ICONS[$platform]}|${platform[@]^}" )
    fi

    if [[ "${query}" = " Go back" ]]; then
      main
    elif [[ -n "$query" ]]; then
      url=${URLS[$platform]}$query
      xdg-open "$url"
    else
      exit
    fi

  else
    exit
  fi
}

main

exit 0
